@root = http://c23f40f579fb.ngrok.io


# POST http://c23f40f579fb.ngrok.io/mail

POST @root/mail
Content-Type: application/json

{"headers" : {"subj": "s"}, "plain": "10.10.196.196"}



# docs:   https://progress-draw-test.wl.r.appspot.com/api/ui/#/person/confrim_prize_assignment

GET  https://c23f40f579fb.ngrok.io